# DO NOT REMOVE THIS
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "Elise Volkman"
languageCode = "en-us"
baseURL = "https://elisevolkman.com"
copyright = "© Elise Volkman {year}"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalyticsID = "G-7Y2V9C7WHS" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/elise_volkman"
  # github = "https://github.com/<your handle>"
  email = "mailto:elisebbt@gmail.com"
  facebook = "https://facebook.com/elisevolkmanediting"
  instagram = "https://instagram.com/elise_is_writing"
  linkedin = "https://ca.linkedin.com/in/elisevolkman"
  youtube = "https://www.youtube.com/channel/UC7JtmODTHbmmcBNfFiNydnA"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["Instagram", "LinkedIn", "YouTube", "Email"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "home"
  name = "home"
  title = "home"
  url = "/"
  weight = -110

[[menu.main]]
  identifier = "author"
  name = "author"
  title = "author"
  url = "/author"
  weight = -100

[[menu.main]]
  identifier = "editor"
  name = "editor"
  title = "editor"
  url = "/editor"
  weight = -90

[[menu.main]]
  identifier = "tea granny"
  name = "tea granny"
  title = "tea granny"
  url = "https://shows.acast.com/the-tea-grannies"
  weight = -80

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = -70